### ISSUE TITLE
Pulumi security improvement suggestions

### ISSUE THREAD

**Issue by renehonig** [pulumi/.github#3]
As a user of Pulumi software, I expect everything is done to ensure the security of the products I am using, especially given the increased number and severity of supply chain attacks. I noticed that there are a number of visible omissions to what are considered good security practices:

- There is no security policy set for the Pulumi Github organization (this #2 PR aims to address that)
- The Pulumi Github organization has not been verified (Cf. [Github documentation](https://docs.github.com/en/organizations/managing-organization-settings/verifying-or-approving-a-domain-for-your-organization))
- Not all commits in the public repositories are signed. (reads this [blog post](https://cybermundus.com/post/git-spoofing/) from Cybermundus to understand the importance of signed commits)
- There is no coordinated vulnerability disclosure policy on the Pulumi website (or at least it is very hard to find)

This list is not exhaustive, but I hope it makes a small contribution to the security of your valuable solution.

**Comment by leezen** [comment]
@ReneHonig Thank you for all these suggestions!

I've opened https://github.com/pulumi/.github/pull/5 to address the disclosure policy issues you brought up.

Thanks also for bringing up the verified issue. We actually intended to be verified and had already verified our domain, but it appears that the site URL has to match exactly (no 'www'), so I've updated the URL and the badge now shows up.

I think we'll need to consider the cost-benefits of signed commits. I think it will add some friction for contributors, but will discuss with the team to see if we think this is something we'd want to enforce.

**Comment by renehonig** [comment]
@leezen, thanks for your response and glad that you found the suggestions helpful. 

On the subject of signed commits, I understand the reluctance, but in my experience it also helps to increase security awareness under developers and maybe some friction is ok (do you want contributions from people that are not able/willing to sign a commit..?) Also, be aware that open source projects are actively targeted in supply chain attacks and signed commit form a (small) part of your defense mechanism. 

I personally find [this guide](https://github.com/drduh/YubiKey-Guide) on how to setup a Yubikey for GPG encryption, signing and authentication (and as SSH key as a bonus) very helpful.
